line1 = input()
line2 = input()
list1 = line1.split(" ")
list2 = line2.split(" ")
a1 = float(list1[1])
a2 = float(list1[2])
b1 = float(list2[1])
b2 = float(list2[2])
value = ((a1*a2)+(b1*b2))
print("VALOR A PAGAR: R$ %.2f" % value)