s = input()
list1 = s.split(" ")
A = float(list1[0])
B = float(list1[1])
C = float(list1[2])
triangulo = ((A*C)/2)
circulo = (3.14159 * pow(C,2))
trapezio = (((A+B)*C)/2)
quadrado = pow(B,2)
retangulo = (A*B)
print("TRIANGULO: %.3f" % triangulo)
print("CIRCULO: %.3f" % circulo)
print("TRAPEZIO: %.3f" % trapezio)
print("QUADRADO: %.3f" % quadrado)
print("RETANGULO: %.3f" % retangulo)